<?php

class LanguageTableSeeder extends Seeder {

	public function run()
	{
		DB::table('languages')->delete();
		DB::table('languages')->insert($this->getData());
	}

	private function getData()
	{
		$array = array(
			array('name' => 'Abkhazian', 'iso_639-1' => 'ab'),
			array('name' => 'Afar', 'iso_639-1' => 'aa'),
			array('name' => 'Afrikaans', 'iso_639-1' => 'af'),
			array('name' => 'Akan', 'iso_639-1' => 'ak'),
			array('name' => 'Albanian', 'iso_639-1' => 'sq'),
			array('name' => 'Amharic', 'iso_639-1' => 'am'),
			array('name' => 'Arabic', 'iso_639-1' => 'ar'),
			array('name' => 'Aragonese', 'iso_639-1' => 'an'),
			array('name' => 'Armenian', 'iso_639-1' => 'hy'),
			array('name' => 'Assamese', 'iso_639-1' => 'as'),
			array('name' => 'Avaric', 'iso_639-1' => 'av'),
			array('name' => 'Avestan', 'iso_639-1' => 'ae'),
			array('name' => 'Aymara', 'iso_639-1' => 'ay'),
			array('name' => 'Azerbaijani', 'iso_639-1' => 'az'),
			array('name' => 'Bambara', 'iso_639-1' => 'bm'),
			array('name' => 'Bashkir', 'iso_639-1' => 'ba'),
			array('name' => 'Basque', 'iso_639-1' => 'eu'),
			array('name' => 'Belarusian', 'iso_639-1' => 'be'),
			array('name' => 'Bengali', 'iso_639-1' => 'bn'),
			array('name' => 'Bihari languages', 'iso_639-1' => 'bh'),
			array('name' => 'Bislama', 'iso_639-1' => 'bi'),
			array('name' => 'Bosnian', 'iso_639-1' => 'bs'),
			array('name' => 'Breton', 'iso_639-1' => 'br'),
			array('name' => 'Bulgarian', 'iso_639-1' => 'bg'),
			array('name' => 'Burmese', 'iso_639-1' => 'my'),
			array('name' => 'Catalan', 'iso_639-1' => 'ca'),
			array('name' => 'Central Khmer', 'iso_639-1' => 'km'),
			array('name' => 'Chamorro', 'iso_639-1' => 'ch'),
			array('name' => 'Chechen', 'iso_639-1' => 'ce'),
			array('name' => 'Chichewa', 'iso_639-1' => 'ny'),
			array('name' => 'Chinese', 'iso_639-1' => 'zh'),
			array('name' => 'Church Slavic', 'iso_639-1' => 'cu'),
			array('name' => 'Chuvash', 'iso_639-1' => 'cv'),
			array('name' => 'Cornish', 'iso_639-1' => 'kw'),
			array('name' => 'Corsican', 'iso_639-1' => 'co'),
			array('name' => 'Cree', 'iso_639-1' => 'cr'),
			array('name' => 'Croatian', 'iso_639-1' => 'hr'),
			array('name' => 'Czech', 'iso_639-1' => 'cs'),
			array('name' => 'Danish', 'iso_639-1' => 'da'),
			array('name' => 'Divehi', 'iso_639-1' => 'dv'),
			array('name' => 'Dutch; Flemish', 'iso_639-1' => 'nl'),
			array('name' => 'Dzongkha', 'iso_639-1' => 'dz'),
			array('name' => 'English', 'iso_639-1' => 'en'),
			array('name' => 'Esperanto', 'iso_639-1' => 'eo'),
			array('name' => 'Estonian', 'iso_639-1' => 'et'),
			array('name' => 'Ewe', 'iso_639-1' => 'ee'),
			array('name' => 'Faroese', 'iso_639-1' => 'fo'),
			array('name' => 'Fijian', 'iso_639-1' => 'fj'),
			array('name' => 'Finnish', 'iso_639-1' => 'fi'),
			array('name' => 'French', 'iso_639-1' => 'fr'),
			array('name' => 'Fulah', 'iso_639-1' => 'ff'),
			array('name' => 'Galician', 'iso_639-1' => 'gl'),
			array('name' => 'Ganda', 'iso_639-1' => 'lg'),
			array('name' => 'Georgian', 'iso_639-1' => 'ka'),
			array('name' => 'German', 'iso_639-1' => 'de'),
			array('name' => 'Greek', 'iso_639-1' => 'el'),
			array('name' => 'Guarani', 'iso_639-1' => 'gn'),
			array('name' => 'Gujarati', 'iso_639-1' => 'gu'),
			array('name' => 'Haitian Creole', 'iso_639-1' => 'ht'),
			array('name' => 'Hausa', 'iso_639-1' => 'ha'),
			array('name' => 'Hebrew', 'iso_639-1' => 'he'),
			array('name' => 'Herero', 'iso_639-1' => 'hz'),
			array('name' => 'Hindi', 'iso_639-1' => 'hi'),
			array('name' => 'Hiri Motu', 'iso_639-1' => 'ho'),
			array('name' => 'Hungarian', 'iso_639-1' => 'hu'),
			array('name' => 'Icelandic', 'iso_639-1' => 'is'),
			array('name' => 'Ido', 'iso_639-1' => 'io'),
			array('name' => 'Igbo', 'iso_639-1' => 'ig'),
			array('name' => 'Indonesian', 'iso_639-1' => 'id'),
			array('name' => 'Interlingua (International Auxiliary Language Association)', 'iso_639-1' => 'ia'),
			array('name' => 'Interlingue', 'iso_639-1' => 'ie'),
			array('name' => 'Inuktitut', 'iso_639-1' => 'iu'),
			array('name' => 'Inupiaq', 'iso_639-1' => 'ik'),
			array('name' => 'Irish', 'iso_639-1' => 'ga'),
			array('name' => 'Italian', 'iso_639-1' => 'it'),
			array('name' => 'Japanese', 'iso_639-1' => 'ja'),
			array('name' => 'Javanese', 'iso_639-1' => 'jv'),
			array('name' => 'Kalaallisut', 'iso_639-1' => 'kl'),
			array('name' => 'Kannada', 'iso_639-1' => 'kn'),
			array('name' => 'Kanuri', 'iso_639-1' => 'kr'),
			array('name' => 'Kashmiri', 'iso_639-1' => 'ks'),
			array('name' => 'Kazakh', 'iso_639-1' => 'kk'),
			array('name' => 'Kikuyu; Gikuyu', 'iso_639-1' => 'ki'),
			array('name' => 'Kinyarwanda', 'iso_639-1' => 'rw'),
			array('name' => 'Kirghiz', 'iso_639-1' => 'ky'),
			array('name' => 'Komi', 'iso_639-1' => 'kv'),
			array('name' => 'Kongo', 'iso_639-1' => 'kg'),
			array('name' => 'Korean', 'iso_639-1' => 'ko'),
			array('name' => 'Kuanyama; Kwanyama', 'iso_639-1' => 'kj'),
			array('name' => 'Kurdish', 'iso_639-1' => 'ku'),
			array('name' => 'Lao', 'iso_639-1' => 'lo'),
			array('name' => 'Latin', 'iso_639-1' => 'la'),
			array('name' => 'Latvian', 'iso_639-1' => 'lv'),
			array('name' => 'Limburgish', 'iso_639-1' => 'li'),
			array('name' => 'Lingala', 'iso_639-1' => 'ln'),
			array('name' => 'Lithuanian', 'iso_639-1' => 'lt'),
			array('name' => 'Luba-Katanga', 'iso_639-1' => 'lu'),
			array('name' => 'Luxembourgish', 'iso_639-1' => 'lb'),
			array('name' => 'Macedonian', 'iso_639-1' => 'mk'),
			array('name' => 'Malagasy', 'iso_639-1' => 'mg'),
			array('name' => 'Malay', 'iso_639-1' => 'ms'),
			array('name' => 'Malayalam', 'iso_639-1' => 'ml'),
			array('name' => 'Maltese', 'iso_639-1' => 'mt'),
			array('name' => 'Manx', 'iso_639-1' => 'gv'),
			array('name' => 'Maori', 'iso_639-1' => 'mi'),
			array('name' => 'Marathi', 'iso_639-1' => 'mr'),
			array('name' => 'Marshallese', 'iso_639-1' => 'mh'),
			array('name' => 'Moldavian; Moldovan', 'iso_639-1' => 'mo'),
			array('name' => 'Mongolian', 'iso_639-1' => 'mn'),
			array('name' => 'Nauru', 'iso_639-1' => 'na'),
			array('name' => 'Navajo; Navaho', 'iso_639-1' => 'nv'),
			array('name' => 'Ndonga', 'iso_639-1' => 'ng'),
			array('name' => 'Nepali', 'iso_639-1' => 'ne'),
			array('name' => 'North Ndebele', 'iso_639-1' => 'nd'),
			array('name' => 'Northern Sami', 'iso_639-1' => 'se'),
			array('name' => 'Norwegian', 'iso_639-1' => 'no'),
			array('name' => 'Norwegian Bokmål', 'iso_639-1' => 'nb'),
			array('name' => 'Norwegian Nynorsk', 'iso_639-1' => 'nn'),
			array('name' => 'Occitan', 'iso_639-1' => 'oc'),
			array('name' => 'Ojibwa', 'iso_639-1' => 'oj'),
			array('name' => 'Oriya', 'iso_639-1' => 'or'),
			array('name' => 'Oromo', 'iso_639-1' => 'om'),
			array('name' => 'Ossetian; Ossetic', 'iso_639-1' => 'os'),
			array('name' => 'Pali', 'iso_639-1' => 'pi'),
			array('name' => 'Panjabi; Punjabi', 'iso_639-1' => 'pa'),
			array('name' => 'Persian', 'iso_639-1' => 'fa'),
			array('name' => 'Polish', 'iso_639-1' => 'pl'),
			array('name' => 'Portuguese', 'iso_639-1' => 'pt'),
			array('name' => 'Pushto; Pashto', 'iso_639-1' => 'ps'),
			array('name' => 'Quechua', 'iso_639-1' => 'qu'),
			array('name' => 'Romanian', 'iso_639-1' => 'ro'),
			array('name' => 'Romansh', 'iso_639-1' => 'rm'),
			array('name' => 'Rundi', 'iso_639-1' => 'rn'),
			array('name' => 'Russian', 'iso_639-1' => 'ru'),
			array('name' => 'Rusyn', 'iso_639-1' => 'ry'),
			array('name' => 'Samoan', 'iso_639-1' => 'sm'),
			array('name' => 'Sango', 'iso_639-1' => 'sg'),
			array('name' => 'Sanskrit', 'iso_639-1' => 'sa'),
			array('name' => 'Sardinian', 'iso_639-1' => 'sc'),
			array('name' => 'Scottish Gaelic', 'iso_639-1' => 'gd'),
			array('name' => 'Serbian', 'iso_639-1' => 'sr'),
			array('name' => 'Serbo-Croatian', 'iso_639-1' => 'sh'),
			array('name' => 'Shona', 'iso_639-1' => 'sn'),
			array('name' => 'Sichuan Yi', 'iso_639-1' => 'ii'),
			array('name' => 'Sindhi', 'iso_639-1' => 'sd'),
			array('name' => 'Sinhalese', 'iso_639-1' => 'si'),
			array('name' => 'Slovak', 'iso_639-1' => 'sk'),
			array('name' => 'Slovenian', 'iso_639-1' => 'sl'),
			array('name' => 'Somali', 'iso_639-1' => 'so'),
			array('name' => 'Sotho, Southern', 'iso_639-1' => 'st'),
			array('name' => 'South Ndebele', 'iso_639-1' => 'nr'),
			array('name' => 'Spanish; Castilian', 'iso_639-1' => 'es'),
			array('name' => 'Sundanese', 'iso_639-1' => 'su'),
			array('name' => 'Swahili', 'iso_639-1' => 'sw'),
			array('name' => 'Swati', 'iso_639-1' => 'ss'),
			array('name' => 'Swedish', 'iso_639-1' => 'sv'),
			array('name' => 'Tagalog', 'iso_639-1' => 'tl'),
			array('name' => 'Tahitian', 'iso_639-1' => 'ty'),
			array('name' => 'Tajik', 'iso_639-1' => 'tg'),
			array('name' => 'Tamil', 'iso_639-1' => 'ta'),
			array('name' => 'Tatar', 'iso_639-1' => 'tt'),
			array('name' => 'Telugu', 'iso_639-1' => 'te'),
			array('name' => 'Thai', 'iso_639-1' => 'th'),
			array('name' => 'Tibetan', 'iso_639-1' => 'bo'),
			array('name' => 'Tigrinya', 'iso_639-1' => 'ti'),
			array('name' => 'Tonga', 'iso_639-1' => 'to'),
			array('name' => 'Tsonga', 'iso_639-1' => 'ts'),
			array('name' => 'Tswana', 'iso_639-1' => 'tn'),
			array('name' => 'Turkish', 'iso_639-1' => 'tr'),
			array('name' => 'Turkmen', 'iso_639-1' => 'tk'),
			array('name' => 'Twi', 'iso_639-1' => 'tw'),
			array('name' => 'Uighur', 'iso_639-1' => 'ug'),
			array('name' => 'Ukrainian', 'iso_639-1' => 'uk'),
			array('name' => 'Urdu', 'iso_639-1' => 'ur'),
			array('name' => 'Uzbek', 'iso_639-1' => 'uz'),
			array('name' => 'Venda', 'iso_639-1' => 've'),
			array('name' => 'Vietnamese', 'iso_639-1' => 'vi'),
			array('name' => 'Volapük', 'iso_639-1' => 'vo'),
			array('name' => 'Walloon', 'iso_639-1' => 'wa'),
			array('name' => 'Welsh', 'iso_639-1' => 'cy'),
			array('name' => 'Western Frisian', 'iso_639-1' => 'fy'),
			array('name' => 'Wolof', 'iso_639-1' => 'wo'),
			array('name' => 'Xhosa', 'iso_639-1' => 'xh'),
			array('name' => 'Yiddish', 'iso_639-1' => 'yi'),
			array('name' => 'Yoruba', 'iso_639-1' => 'yo'),
			array('name' => 'Zhuang; Chuang', 'iso_639-1' => 'za'),
			array('name' => 'Zulu', 'iso_639-1' => 'zu'),
		);
		return $array;
	}

}